apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  namespace: cat
  labels:
    app: cat
spec:
  selector:
    matchLabels:
      app: cat
  replicas: 1
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: local/cat-website
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monkey-deployment
  namespace: monkey
  labels:
    app: monkey
spec:
  selector:
    matchLabels:
      app: monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: monkey
    spec:
      containers:
      - name: monkey
        image: local/monkey-website
        imagePullPolicy: Never
        ports:
        - containerPort: 80