apiVersion: v1
kind: Namespace
metadata:
  name: main-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  namespace: main-namespace
  labels:
    app: cat-app
spec:
  selector:
    matchLabels:
      app: cat-app
  replicas: 2
  template:
    metadata:
      labels:
        app: cat-app
    spec:
      containers:
      - name: cat
        image: 411470295704.dkr.ecr.us-east-1.amazonaws.com/cat-website
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monkey-deployment
  namespace: main-namespace
  labels:
    app: monkey-app
spec:
  selector:
    matchLabels:
      app: monkey-app
  replicas: 2
  template:
    metadata:
      labels:
        app: monkey-app
    spec:
      containers:
      - name: monkey
        image: 411470295704.dkr.ecr.us-east-1.amazonaws.com/monkey-website
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: main-namespace
  labels:
    app: main-app
spec:
  selector:
    matchLabels:
      app: main-app
  replicas: 2
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main-app
        image: 411470295704.dkr.ecr.us-east-1.amazonaws.com/mainpage
        ports:
        - containerPort: 80