apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  namespace: cat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: local/cat-website
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monkey-deployment
  namespace: monkey
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: monkey
    spec:
      containers:
      - name: monkey
        image: local/monkey-website
        ports:
        - containerPort: 80