apiVersion: v1
kind: Namespace
metadata:
  name: main-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  namespace: main-namespace
  labels:
    app: cat
spec:
  selector:
    matchLabels:
      app: cat
  replicas: 1
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: 411470295704.dkr.ecr.us-east-1.amazonaws.com/cat-website
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monkey-deployment
  namespace: main-namespace
  labels:
    app: monkey
spec:
  selector:
    matchLabels:
      app: monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: monkey
    spec:
      containers:
      - name: monkey
        image: 411470295704.dkr.ecr.us-east-1.amazonaws.com/monkey-website
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: main-namespace
  labels:
    app: main
spec:
  selector:
    matchLabels:
      app: main
  replicas: 1
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: 411470295704.dkr.ecr.us-east-1.amazonaws.com/mainpage
        ports:
        - containerPort: 80