apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
spec:
  rules:
  - http:
      paths:
      - path: /app1
        backend:
          serviceName: app1-service
          servicePort: 80
      - path: /app2
        backend:
          serviceName: app2-service
          servicePort: 80