apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
spec:
  rules:
  - http:
      paths:
      - path: /testepath
        backend:
          serviceName: external-service
          servicePort: 80