apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-env
  labels:
    app: secret-env
spec:
  selector:
    matchLabels:
      app: secret-env
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-env
    spec:
      containers:
        - name: secret-env
          image: nginx:latest
          command: ["/bin/bash"]
          args: ["echo  > /usr/share/nginx/html/index.html"]
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-set
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-set
                  key: password