apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: secret-container
      image: nginx
      command: 'echo "<h1>Username: $SECRET_USERNAME Password: $PASSWORD </h1>"'
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-set
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-set
              key: password
  restartPolicy: Never