apiVersion: v1
kind: Service
metadata:
  name: service-cat
  namespace: main-namespace
spec:
  selector:
    app: cat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: main-namespace
  namespace: monkey
spec:
  selector:
    app: monkey-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: service-main
  namespace: main-namespace
spec:
  selector:
    app: main-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort