apiVersion: v1
kind: Service
metadata:
  name: service-cat
  namespace: cat
spec:
  selector:
    app: cat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-monkey
  namespace: monkey
spec:
  selector:
    app: monkey-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-main
  namespace: mainpage
spec:
  selector:
    app: main-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80